import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Header/page";
import Footer from "@/components/Footer";
import SessionProvider from "@/providers/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen dark:bg-black dark:text-white">
          <SessionProvider>
            <Header />
            {/* <div className="container mx-auto -mt-32 max-w-screen-2xl bg-white px-4 dark:bg-black sm:max-w-screen-sm  md:max-w-screen-md md:px-0 lg:max-w-screen-lg xl:max-w-screen-xl"> */}
            <div className="container -mt-32 px-8">
              <Navbar />
              {children}
              <Footer />
            </div>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
